### ISSUE TITLE
Crawl first page error, board_id: xxxxx

### ISSUE THREAD

**Issue by othorizon** [staugur/grab_huaban_board#10]
登录并按用户id 下载的时候，有一些board无法下载。报错 Crawl first page error, board_id: xxxxx

为什么会报这个错？而且在不同的机器运行，出错的board还不一样。

```
[ ERROR ] 2019-03-14 16:49:51 grab_huaban_board.py:MainThread:166:100 ('Connection aborted.', BadStatusLine('V\x0c\xbf\xde5V\xbdt\xa3\x93\xd7\xabU_k\xafq\xfb\xa6_\xc3\x13\x1b<\x19\xae\xb5\xce\x93\xb3\x87\x96W6{\x08\xb8\xd5W\xdd\x809\xca\x19\x05p6q\xfa|\xcc\x11C3\xe7\xdd\x1as\xd9^{/H\xe4\xa4\xb7\xb1\xf2,N\x92D(\xa1\xa8\x8f\x89S\x84;\x1bGR*\xe7\x85MJ/\xce\xd3`\x9f\xd8\x88\xb9\x994\xacqZ\x16\xb1\x07\x90c\x03\xca\\v\xd9(\x82%F\xc2\\k\x13\xd05&\x00\x15\xc2".%Y\x8f\x8b\xfb_\xbf\xbdt\xeb\xf2\xf7\xb7\xdf\xe8\xbe\xf7\xc1\xbd\x9b\x7f\xb9w\xf17\xbd\xd7\xff\xd8\xbbx\xf5\xfb\xdb\xd7\xbe;w\xa9w\xe1j\xf7\xbd\xcf\x04\xf0\xf2\xdd\xb9\xb7\xcb\xfd?\xdd\xe9\xde\xfax?\xf1\xc32\x96\xdf\x15~6F\x82m\xe2\x87\n',))
Traceback (most recent call last):
  File "grab_huaban_board.py", line 97, in _crawl_board
    r = request.get(board_url).json()
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('V\x0c\xbf\xde5V\xbdt\xa3\x93\xd7\xabU_k\xafq\xfb\xa6_\xc3\x13\x1b<\x19\xae\xb5\xce\x93\xb3\x87\x96W6{\x08\xb8\xd5W\xdd\x809\xca\x19\x05p6q\xfa|\xcc\x11C3\xe7\xdd\x1as\xd9^{/H\xe4\xa4\xb7\xb1\xf2,N\x92D(\xa1\xa8\x8f\x89S\x84;\x1bGR*\xe7\x85MJ/\xce\xd3`\x9f\xd8\x88\xb9\x994\xacqZ\x16\xb1\x07\x90c\x03\xca\\v\xd9(\x82%F\xc2\\k\x13\xd05&\x00\x15\xc2".%Y\x8f\x8b\xfb_\xbf\xbdt\xeb\xf2\xf7\xb7\xdf\xe8\xbe\xf7\xc1\xbd\x9b\x7f\xb9w\xf17\xbd\xd7\xff\xd8\xbbx\xf5\xfb\xdb\xd7\xbe;w\xa9w\xe1j\xf7\xbd\xcf\x04\xf0\xf2\xdd\xb9\xb7\xcb\xfd?\xdd\xe9\xde\xfax?\xf1\xc32\x96\xdf\x15~6F\x82m\xe2\x87\n',))
[ ERROR ] 2019-03-14 16:49:51 grab_huaban_board.py:MainThread:165:100 ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: invalid distance too far back',))
Traceback (most recent call last):
  File "grab_huaban_board.py", line 97, in _crawl_board
    r = request.get(board_url).json()
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 755, in generate
    raise ContentDecodingError(e)
ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing: invalid distance too far back',))
```

**Comment by staugur** [comment]
看错误是因为请求huaban.com导致的，可以把user_id发下吗

**Comment by othorizon** [comment]
> 看错误是因为请求huaban.com导致的，可以把user_id发下吗

事实上，我尝试采集任何用户的，都会出现这个问题。

**Comment by staugur** [comment]
下午看下

**Comment by staugur** [comment]
> > 看错误是因为请求huaban.com导致的，可以把user_id发下吗
> 
> 事实上，我尝试采集任何用户的，都会出现这个问题。

请更新下代码重试下，问题应该是解码返回时出现错误，猜测可能请求频率导致，现增加了暂停和重试。
修改代码后测试两个user_id，基本无异常。

另外，你可以尝试js版油猴脚本。

**Comment by othorizon** [comment]
> > > 看错误是因为请求huaban.com导致的，可以把user_id发下吗
> > 
> > 
> > 事实上，我尝试采集任何用户的，都会出现这个问题。
> 
> 请更新下代码重试下，问题应该是解码返回时出现错误，猜测可能请求频率导致，现增加了暂停和重试。
> 修改代码后测试两个user_id，基本无异常。
> 
> 另外，你可以尝试js版油猴脚本。

好的 非常感谢～～
